src/Howest.Prog.CoinChop.Web/Models/ExpenseGroupModels/DashboardViewModel.cs
using Howest.Prog.CoinChop.Core.Entities;
using System.Collections.Generic;

namespace Howest.Prog.CoinChop.Web.Models.ExpenseGroupModels
{
    public class DashboardViewModel
    {
        public long GroupId { get; set; }

        public string Name { get; set; }

        public string GroupToken { get; set; }

        public IEnumerable<Member> Members { get; set; }

        public IEnumerable<Expense> SharedExpenses { get; set; }

        public IEnumerable<Debt> Transactions { get; set; }
    }
}

src/Howest.Prog.CoinChop.Web/Controllers/ExpenseController.cs
using Howest.Prog.CoinChop.Core.Common;
using Howest.Prog.CoinChop.Core.Interfaces;
using Howest.Prog.CoinChop.Core.Models.ExpenseService;
using Howest.Prog.CoinChop.Core.Services;
using Howest.Prog.CoinChop.Web.Extensions;
using Howest.Prog.CoinChop.Web.Models.ExpenseModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace Howest.Prog.CoinChop.Web.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly ExpenseService _expenseService;
        private readonly MemberService _memberService;
        private readonly IExpenseGroupRepository _expenseGroupRepository;
        private readonly IMemberRepository _memberRepository;
        private readonly IMailService _notificationService;

        public ExpenseController(
            ExpenseService expenseService,
            MemberService memberService,
            IExpenseGroupRepository expenseGroupRepository,
            IMemberRepository memberRepository,
            IMailService notificationService) 
        {
            _expenseService = expenseService;
            _memberService = memberService;
            _expenseGroupRepository = expenseGroupRepository;
            _memberRepository = memberRepository;
            _notificationService = notificationService;
        }

        public IActionResult Add([FromRoute] string groupToken)
        {
            var viewModel = new AddExpenseViewModel();
            viewModel.GroupToken = groupToken;
            viewModel.Contributors = PopulateContributors(groupToken);
            viewModel.AddExpenseInput = new AddExpenseInput
            {
                Amount = 0M
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Add(AddExpenseInput addExpenseInput, [FromRoute] string groupToken)
        {
            try
            {
                //execute command
                AddExpenseResult result = _expenseService.AddExpenseToGroup(addExpenseInput);

                //determine HTTP output
                if (result.IsSuccess)
                {
                    //return to dashboard
                    return RedirectToAction(nameof(ExpenseGroupController.Dashboard),
                                            "ExpenseGroup",
                                            new { groupToken });
                }
                else
                {
                    //add validation errors to ASP.Net model state
                    ModelState.MapValidationResults(result.ValidationResults, "AddExpenseInput.");

                    //redisplay form
                    var viewModel = new AddExpenseViewModel
                    {
                        AddExpenseInput = addExpenseInput,
                        GroupToken = groupToken,
                        Contributors = PopulateContributors(groupToken),
                    };
                    return View(viewModel);
                }
            }
            catch (EntityNotFoundException)
            {
                return BadRequest();
            }
        }

        [HttpPost]
        public IActionResult Remove(long id, [FromRoute] string groupToken)
        {
            try
            {
                //execute command
                RemoveExpenseResult result = _expenseService.RemoveExpense(id);

                //determine HTTP output
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(ExpenseGroupController.Dashboard),
                                            "ExpenseGroup",
                                            new { groupToken });
                }
                else
                {
                    return BadRequest();
                }
            }
            catch (EntityNotFoundException)
            {
                return BadRequest();
            }
        }

        private IEnumerable<SelectListItem> PopulateContributors(string groupToken)
        {
            List<SelectListItem> membersList = null;
            var group = _expenseGroupRepository.GetByToken(groupToken);
            if (group != null)
            {
                membersList = _memberRepository.GetByGroup(group.Id).Select(
                    member => new SelectListItem { Value = member.Id.ToString(), Text = $"{member.Name} ({member.Email})" }    
                ).ToList();
                membersList.Insert(0, new SelectListItem { Value = "0", Text = $"==== pick a contributor ====" });
            }
            return membersList;
        }
    }
}

src/Howest.Prog.CoinChop.Web/Controllers/ExpenseGroupController.cs
using Howest.Prog.CoinChop.Core.Common;
using Howest.Prog.CoinChop.Core.Interfaces;
using Howest.Prog.CoinChop.Core.Models.DebtCalculator;
using Howest.Prog.CoinChop.Core.Models.ExpenseGroupService;
using Howest.Prog.CoinChop.Core.Services;
using Howest.Prog.CoinChop.Web.Extensions;
using Howest.Prog.CoinChop.Web.Models;
using Howest.Prog.CoinChop.Web.Models.ExpenseGroupModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Linq;

namespace Howest.Prog.CoinChop.Web.Controllers
{
    public class ExpenseGroupController : Controller
    {
        private readonly IMailService _notificationService;
        private readonly ExpenseGroupService _expenseGroupService;
        private readonly DebtCalculator _debtCalculator;

        public ExpenseGroupController(
            IMailService notificationService, 
            ExpenseGroupService expenseGroupService,
            DebtCalculator debtCalculator)
        {
            _notificationService = notificationService;
            _expenseGroupService = expenseGroupService;
            _debtCalculator = debtCalculator;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AccessDashboard(AccessExpenseGroupInput accessInput)
        {
            if (accessInput.Token != null) 
            {
                return RedirectToAction(nameof(Dashboard), new { groupToken = accessInput.Token });
            }
            else 
            {
                return RedirectToAction(nameof(Index));
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateGroupInput createInput)
        {
            //execute command
            CreateGroupResult result = _expenseGroupService.CreateGroup(createInput);

            //determine HTTP output
            if (result.IsSuccess)
            {
                return RedirectToAction(nameof(Dashboard), new { groupToken = result.GeneratedToken });
            }
            else
            {
                //add validation errors to ASP.Net model state
                ModelState.MapValidationResults(result.ValidationResults);

                //redisplay form
                return View(createInput);
            }
        }

        [HttpGet]
        public IActionResult Dashboard([FromRoute] string groupToken)
        {
            try
            {
                var result = _expenseGroupService.ViewExpenseGroup(groupToken);

                if (result.IsSuccess)
                {
                    var viewModel = new DashboardViewModel
                    {
                        GroupId = result.Group.Id,
                        Name = result.Group.Name,
                        GroupToken = result.Group.Token,
                        Members = result.Group.Members,
                        SharedExpenses = result.Group.Members.SelectMany(e => e.Contributions).OrderBy(c => c.Id)
                    };

                    var calculateInput = new CalculateDebtInput { GroupId = result.Group.Id };
                    var calculatedResult = _debtCalculator.CalculateDebt(calculateInput);

                    if (calculatedResult.IsSuccess)
                    {
                        viewModel.Transactions = calculatedResult.Debts;
                        return View(viewModel);
                    }
                    else
                    {
                        throw new ApplicationException("Calculation failed");
                    }
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch(EntityNotFoundException)
            {
                return NotFound();
            }
        }


        [HttpPost]
        public IActionResult ReplaceToken(ReplaceTokenInput replaceInput)
        {
            //execute command
            ReplaceTokenResult result = _expenseGroupService.ReplaceGroupToken(replaceInput);

            //determine HTTP output
            if (result.IsSuccess)
            {
                return RedirectToAction(nameof(Dashboard), new { groupToken = result.NewToken });
            }
            else
            {
                //add validation errors to ASP.Net model state
                ModelState.MapValidationResults(result.ValidationResults, "ReplaceGroupTokenInput.");

                //redisplay form
                return View(replaceInput);
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Howest.Prog.CoinChop.Web/Controllers/MemberController.cs
using Howest.Prog.CoinChop.Core.Common;
using Howest.Prog.CoinChop.Core.Interfaces;
using Howest.Prog.CoinChop.Core.Models.MemberService;
using Howest.Prog.CoinChop.Core.Services;
using Howest.Prog.CoinChop.Web.Extensions;
using Howest.Prog.CoinChop.Web.Models.MemberModels;
using Microsoft.AspNetCore.Mvc;

namespace Howest.Prog.CoinChop.Web.Controllers
{
    public class MemberController : Controller
    {
        private readonly IMailService _notificationService;
        private readonly IExpenseGroupRepository _expenseGroupRepository;
        private readonly MemberService _memberService;

        public MemberController(IMailService notificationService, 
            MemberService memberService,
            IExpenseGroupRepository expenseGroupRepository)
        {
            _notificationService = notificationService;
            _memberService = memberService;
            _expenseGroupRepository = expenseGroupRepository;
        }

        public IActionResult Add([FromRoute] string groupToken)
        {
            var group = _expenseGroupRepository.GetByToken(groupToken);
            if(group == null)
            {
                return BadRequest();
            }
            else
            {
                var viewModel = new AddMemberViewModel
                {
                    GroupToken = groupToken,
                    AddMemberInput = new AddMemberInput { GroupId = group.Id }
                };
                return View(viewModel);
            }
        }

        [HttpPost]
        public IActionResult Add(AddMemberInput addMemberInput, [FromRoute] string groupToken)
        {
            try
            {
                //execute command
                AddMemberResult result = _memberService.AddMemberToGroup(addMemberInput);

                //determine HTTP output
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(ExpenseGroupController.Dashboard),
                                            "ExpenseGroup",
                                            new { groupToken });
                }
                else
                {
                    //add validation errors to ASP.Net model state
                    ModelState.MapValidationResults(result.ValidationResults, "AddMemberInput.");

                    //redisplay form
                    var viewModel = new AddMemberViewModel
                    {
                        AddMemberInput = addMemberInput,
                        GroupToken = groupToken
                    };
                    return View(viewModel);
                }
            }
            catch (EntityNotFoundException)
            {
                return BadRequest();
            }
        }

        [HttpPost]
        public IActionResult Remove(long id, [FromRoute] string groupToken)
        {
            try
            {
                //execute command
                RemoveMemberResult result = _memberService.RemoveMemberFromGroup(id);

                //determine HTTP output
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(ExpenseGroupController.Dashboard),
                                            "ExpenseGroup",
                                            new { groupToken });
                }
                else
                {
                    return BadRequest();
                }
            }
            catch (EntityNotFoundException)
            {
                return BadRequest();
            }
        }
    }
}

src/Howest.Prog.CoinChop.Web/Views/ExpenseGroup/Create.cshtml
@model CreateGroupInput

@{
    ViewData["Title"] = "Create new group";
}

<br />
<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back</a>
</div>

src/Howest.Prog.CoinChop.Web/Views/ExpenseGroup/Dashboard.cshtml
@model DashboardViewModel
@{
    ViewData["Title"] = Model.Name + " - dashboard";
    var fullUrl = this.Url.Action("Dashboard", "ExpenseGroup", new { groupToken = Model.GroupToken }, this.Context.Request.Scheme);
}

<div class="row">
    <div class="col-lg-12">
        <h2>@ViewData["Title"]</h2>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="well">
            <p>This group is visible for anyone who visits this unique link: <a href="@fullUrl">@fullUrl</a></p>
            <p class="text-center"></p>
            <form class="text-center" asp-action="ReplaceToken" asp-route-groupToken="@Model.GroupToken">
                <input type="hidden" asp-for="@Model.GroupId" />
                <input type="hidden" asp-for="@Model.GroupToken" id="CurrentToken" name="CurrentToken" />
                <button type="submit" class="btn btn-warning btn-xs"><span class="button-icon">&#11118;</span> Regenerate shared link</button>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-9 col-md-9 col-sm-12">
        <table class="table table-striped">
            <caption>
                <h3 class="section-header section-header-dashboard"><img src="~/images/members.png" alt="members" /> Members</h3>
            </caption>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>E-mail</th>
                    <th width="1%"><a asp-action="add" asp-controller="Member" asp-route-groupToken="@Model.GroupToken" 
                           class="btn btn-primary pull-right pull-right"><span class="button-icon">＋</span> Add member</a></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var member in Model.Members)
                {
                    long id = member.Id;
                    <tr>
                        <td>@member.Name</td>
                        <td>@member.Email</td>
                        <td>
                            <form asp-action="remove" asp-controller="Member" asp-route-groupToken="@Model.GroupToken">
                                <input type="hidden" asp-for="@id" />
                                <button type="submit" class="btn btn-xs pull-right">&#10060;</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>
<div class="row">
    <div class="col-lg-9 col-md-9 col-sm-12">
        <table class="table table-striped">
            <caption>
                <h3 class="section-header section-header-dashboard"><img src="~/images/coin.png" alt="Expenses" /> Expenses</h3>
            </caption>
            <thead>
                <tr>
                    <th>Member</th>
                    <th width="20%" class="text-center">Contribution</th>
                    <th>Description</th>
                    <th width="1%"><a asp-action="add" asp-controller="Expense" asp-route-groupToken="@Model.GroupToken"
                           class="btn btn-primary pull-right"><span class="button-icon">＋</span> Add expense</a></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var expense in Model.SharedExpenses)
                {
                    long id = expense.Id;
                    <tr>
                        <td>@expense.Contributor.Name</td>
                        <td class="text-right text-danger bg-negative-amount">€ @expense.Amount.ToString("N2")</td>
                        <td>@expense.Description</td>
                        <td>
                            <form asp-action="remove" asp-controller="Expense" asp-route-groupToken="@Model.GroupToken">
                                <input type="hidden" asp-for="@id" />
                                <button type="submit" class="btn btn-xs pull-right">&#10060;</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td class="text-right text-danger expenses-total-amount">€ @Model.SharedExpenses.Sum(expense => expense.Amount).ToString("N2")</td>
                    <td colspan="2" class="expenses-total-label">Total</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-lg-9 col-md-9 col-sm-12">
        @if (Model.Transactions.Count() == 0) {
            <div class="alert alert-success">
                No compensations needed between members
            </div>
        }
        else
        {
            <table class="table table-striped">
                <caption>
                    <h3 class="section-header section-header-dashboard"><img src="~/images/chop.png" alt="Chops" /> Chops</h3>
                </caption>
                <thead>
                    <tr>
                        <th class="text-center">Debt</th>
                        <th colspan="3" class="text-center">Transaction</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var transaction in Model.Transactions)
                    {
                        <tr>
                            <td width="20%" class="text-right text-danger transaction-amount">€ @transaction.Amount.ToString("N2")</td>
                            <td width="39%" class="text-right transaction-member">@transaction.Debtor.Name</td>
                            <td width="2%" class="transaction-arrow">&#129146;</td>
                            <td width="39%" class="text-left transaction-member">@transaction.Creditor.Name</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

src/Howest.Prog.CoinChop.Web/Views/ExpenseGroup/Index.cshtml
@model AccessExpenseGroupInput
@{
    ViewData["Title"] = "Coin chop";
}

<br />

<div class="row">
    <div class="col-md-5">
        <h3>Access your group dashboard</h3>
        <br />
        <form method="post" asp-action="AccessDashboard" asp-controller="ExpenseGroup" class="form-inline">
            <div class="form-group">
                <label asp-for="Token">Group token</label>
                <input asp-for="Token" class="form-control" autocomplete="off">
            </div>
            <input type="submit" value="Submit" class="form-control btn btn-primary" />
        </form>
    </div>
    <div class="col-md-2 text-center text-capitalize landing-choice-label">or</div>
    <div class="col-md-5">
        <h3>Split costs with a group</h3>
        <br />
        <div class="text-left"><a asp-action="Create" class="btn btn-primary">Start a new group</a></div>
    </div>
</div>